### ISSUE TITLE
Hittesting with scale 0 in release mode (osx)

### ISSUE THREAD

**Issue by lab101** [Potion/Cinder-poScene#48]
Hey,

Just discovered a small bug in the hittesting of the nodes.
When setting a node to a scale where x or y is zero it get's a hit wherever you click in the scene.

You can reproduce this in the MouseEventsSample.
Set one of the squares to scale zero.
mSquareContainer->getChildByIndex(0)->setScale(0, 1);

When running in release mode it wil give a "down inside" wherever you click..
In debug mode it works fine...

As a workaround I set my node invisible when scaling is 0.

**Comment by kitschpatrol** [comment]
Having the same issue.

**Comment by kitschpatrol** [comment]
Possibly related: https://forum.libcinder.org/topic/unproject-problems-returning-nan

**Comment by lab101** [comment]
Ah your right the unproject returns indeed NAN when doing a = glm::inverse(a);
I also replace the unproject with the glm::unproject which is giving the same result.

**Comment by kitschpatrol** [comment]
Yes, I also just tried the GLM implementation... same result. But even in debug mode the scene graph seems to cope the NAN results successfully, so I'm trying to figure out what's different about an optimized build.

I think we're getting NAN any time the model view matrix passed into unproject has zero values in the a and f positions.

**Comment by kitschpatrol** [comment]
I think I found it, in a debug build Rect.h's contains method returns false if passed a vec2(NAN, NAN)... in a release built it returns true!

**Comment by kitschpatrol** [comment]
The ugly fix is just to check for NAN values in the hit test in poNode.cpp:

```
//
//  This is used for hit-testing all Nodes
//  Override this function to do any type of custom
//
bool Node::pointInside(const ci::vec2 &point) {
	ci::vec2 pos = windowToLocal(point);
	return getBounds().contains(pos) && !std::isnan(pos.x);
}
```

Not crazy about this since poNode.cpp subclasses would have to know to make the same check if they override pointInside... but it also doesn't really make sense to add a check to Cinder's Rect.h since NAN inputs deservedly yield undefined behavior?

Any ideas on the best way forward?

**Comment by vtron** [comment]
Whoa! Sorry I am just seeing this, looks like my issue notifications were turned off :(

Man this is a tough bug, NaN is rough based on current implementation. 

I pushed a clean fix that specifically fixes this case, but I may have to do more thinking about fixing this at a deeper level in the Node transformations (windowToLocal, localToWindow), the only thing I can think of right now is check for NaN and return something like ci::vec3(std::min<float>, std::min<float>) with a warning and explanation. 

The pointInside override is indeed not ideal, we override pointInside for a lot of reasons and having this dependency is definitely a point of failure in the future.

I added a scale check to 'isEligibleForInteraction' which is a method I use internally with the EventCenter, it seems like the most appropriate place and shouldn't be anything that is overridden. Just pushed please check it out and let me know!

Also, another note, I also could not reproduce in Debug but consistently had the error in Release

**Comment by kitschpatrol** [comment]
Thanks, yes this fixes is — and isEligibleForInteraction is a much better place to put the check than pointInside.

I'm also only seeing the original bug in release builds. I think Rectf's contains function is handling nan input differently depending on the build type. (However I'm having trouble writing a truly minimal test case... just passing contains a nan vec2 in other contexts doesn't seem to trigger it.)

Anyway thanks for your help and for a great library.

**Comment by lab101** [comment]
Just tested and the scale check in isEligibleForInteraction does the job.
